# Generated by Django 5.2.5 on 2025-10-17 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('sac_code', models.CharField(default='999293', max_length=10)),
                ('client_name', models.TextField(default='TO: THE COMMANDING OFFICER,')),
                ('client_address', models.TextField(default='21 CGSR (A), BAIRAGARH, BHOPAL, MADHYA PRADESH-462031, INDIA')),
                ('contract_no', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('service_description', models.TextField(default='Mode of training: offline\nTraining frequency: Weekdays\nDuration of training per day (in hours): 4\nTraining premise: Buyers location\nType of training: Classroom based Instructor Led Training\nCourse level: Intermediate\nCategory of training course: IT and Software\nSub-categories of training course: Network and Security\nCertification: Yes\nCertification programme: Participation Certificate\nType of training partner: Training institute')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(default='Uttarakhand', max_length=100)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.signature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
